### ISSUE TITLE
Inspection issue for targets

### ISSUE THREAD

**Issue by pySilver** [anstarovoyt/intellij-stimulus#1]
Inspection complains about the following `data-mega-menu-target="link dropdown"` while Stimulus accepts multiple targets within controller/element.

**Comment by anstarovoyt** [comment]
thanks! I will fix it asap

**Comment by anstarovoyt** [comment]
Hi! Fixed in 0.0.2. Unfortunately I had to disable the inspection completely, but the top level completion still works.
