### ISSUE TITLE
Support kebab-case controller file names

### ISSUE THREAD

**Issue by matteocontrini** [anstarovoyt/intellij-stimulus#11]
Currently only controllers named `camel_case_controller.js` are detected, but the Stimulus documentation explicitly mentions that `kebab-case-controller.js` is also an accepted naming convention.

https://stimulus.hotwired.dev/handbook/installing

It would be great if this plugin supported that format too.

Thanks!

**Comment by anstarovoyt** [comment]
Fixed, going to publish update soon
