### ISSUE TITLE
Can you update for compatibility with the impending 2024 release?

### ISSUE THREAD

**Issue by hms** [anstarovoyt/intellij-stimulus#16]
@anstarovoyt 

First, thank you for the plugin.  I find in very valuable.

I tried to fork and update the build myself, but I'm running into some weirdness around the plugin libraries and since I don't have any experience with the Java build world, quickly got past my ability to solve on my own.

Would it be possible for you to drop a new release anytime soon? I'm asking because if you are unable to, or uninterested in, supporting the plugin for whatever reasons then I know that I shouldn't wait on the Rubymine upgrade.

Thanks you.

**Comment by anstarovoyt** [comment]
@hms hello! I will update the plugin this week

**Comment by hms** [comment]
@anstarovoyt Thank you!  

Again, really appreciate the help from the plugin and your willingness to help.

hms
