### ISSUE TITLE
please update for latest IDE

### ISSUE THREAD

**Issue by landsman** [anstarovoyt/intellij-stimulus#17]
![Screenshot 2024-08-13 at 18 01 14](https://github.com/user-attachments/assets/ca9515f7-2485-4e6a-935c-2d559065c77f)

**Comment by MelaineGerard** [comment]
A good idea would be to archive this project so people won't try to use it

**Comment by landsman** [comment]
> A good idea would be to archive this project so people won't try to use it

yes!
