### ISSUE TITLE
Incompatibility issue

### ISSUE THREAD

**Issue by CyrilKrylatov** [anstarovoyt/intellij-stimulus#19]
Hello,

The plugin is no longer compatible with the latest WebStorm build as per seen here:

![image](https://github.com/user-attachments/assets/beb8b95c-5e01-44e8-b76e-ebb12bac48d9)

Thank you for the time that you puts in this very useful plugin!

Cheers.

**Comment by anstarovoyt** [comment]
Hello! Please, remove the old plugin and install a new one by JetBrains https://plugins.jetbrains.com/plugin/24562-stimulus. It is a fork of the plugin and it has new features.

**Comment by CyrilKrylatov** [comment]
Oh I was writting a message about that. Sorry I didn't catch it before opening an issue.

Thank you for your answer, have a nice day!
